<a href="https://colab.research.google.com/github/KristinaA96/_DTSC3020_Fall2025/blob/main/assignment_6_webscraping_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 6 (4 points) — Web Scraping

In this assignment you will complete **two questions**. The **deadline is posted on Canvas**.

## Assignment Guide (Read Me First)

- This notebook provides an **Install Required Libraries** cell and a **Common Imports & Polite Headers** cell. Run them first.
- Each question includes a **skeleton**. The skeleton is **not** a solution; it is a lightweight scaffold you may reuse.
- Under each skeleton you will find a **“Write your answer here”** code cell. Implement your scraping, cleaning, and saving logic there.
- When your code is complete, run the **Runner** cell to print a Top‑15 preview and save the CSV.
- Expected outputs:
  - **Q1:** `data_q1.csv` + Top‑15 sorted by the specified numeric column.
  - **Q2:** `data_q2.csv` + Top‑15 sorted by `points`.

In [ ]:
1) #Install Required Libraries
!pip -q install requests beautifulsoup4 lxml pandas
print("Dependencies installed.")

SyntaxError: unmatched ')' (ipython-input-565355372.py, line 1)

### 2) Common Imports & Polite Headers

In [ ]:
# Common Imports & Polite Headers
import re, sys, pandas as pd, requests
from bs4 import BeautifulSoup
HEADERS = {"User-Agent": (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/122.0 Safari/537.36")}
def fetch_html(url: str, timeout: int = 20) -> str:
    r = requests.get(url, headers=HEADERS, timeout=timeout)
    r.raise_for_status()
    return r.text
def flatten_headers(df: pd.DataFrame) -> pd.DataFrame:
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [" ".join([str(x) for x in tup if str(x)!="nan"]).strip()
                      for tup in df.columns.values]
    else:
        df.columns = [str(c).strip() for c in df.columns]
    return df
print("Common helpers loaded.")

## Question 1 — IBAN Country Codes (table)
**URL:** https://www.iban.com/country-codes  
**Extract at least:** `Country`, `Alpha-2`, `Alpha-3`, `Numeric` (≥4 cols; you may add more)  
**Clean:** trim spaces; `Alpha-2/Alpha-3` → **UPPERCASE**; `Numeric` → **int** (nullable OK)  
**Output:** write **`data_q1.csv`** and **print a Top-15** sorted by `Numeric` (desc, no charts)  
**Deliverables:** notebook + `data_q1.csv` + short `README.md` (URL, steps, 1 limitation)

**Tip:** You can use `pandas.read_html(html)` to read tables and then pick one with ≥3 columns.

In [ ]:
# --- Q1 Skeleton (fill the TODOs) ---
def q1_read_table(html: str) -> pd.DataFrame:
    """Return the first table with >= 3 columns from the HTML.
    TODO: implement with pd.read_html(html), pick a reasonable table, then flatten headers.
    """
    raise NotImplementedError("TODO: implement q1_read_table")

def q1_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean columns: strip, UPPER Alpha-2/Alpha-3, cast Numeric to int (nullable), drop invalids.
    TODO: implement cleaning steps.
    """
    raise NotImplementedError("TODO: implement q1_clean")

def q1_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort descending by Numeric and return Top-N.
    TODO: implement.
    """
    raise NotImplementedError("TODO: implement q1_sort_top")

In [ ]:
URL_Q1 = "https://www.iban.com/country-codes"
html_content_q1 = fetch_html(URL_Q1)
print("HTML content fetched for Question 1.")

HTML content fetched for Question 1.

In [ ]:
import requests

HEADERS = {"User-Agent": (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/122.0 Safari/537.36")}

def fetch_html(url: str, timeout: int = 20) -> str:
    r = requests.get(url, headers=HEADERS, timeout=timeout)
    r.raise_for_status()
    return r.text

URL_Q1 = "https://www.iban.com/country-codes"
html_content_q1 = fetch_html(URL_Q1)
print("HTML content fetched for Question 1.")

HTML content fetched for Question 1.

In [ ]:
import pandas as pd

def flatten_headers(df: pd.DataFrame) -> pd.DataFrame:
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [" ".join([str(x) for x in tup if str(x)!="nan"]).strip()
                      for tup in df.columns.values]
    else:
        df.columns = [str(c).strip() for c in df.columns]
    return df

def q1_read_table(html: str) -> pd.DataFrame:
    dfs = pd.read_html(html)
    for df in dfs:
        if df.shape[1] >= 3:
            return flatten_headers(df)
    raise ValueError("No suitable table found with at least 3 columns.")

df_q1 = q1_read_table(html_content_q1)
print("Table extracted into DataFrame.")
df_q1.head()

Table extracted into DataFrame.

/tmp/ipython-input-1847083582.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(html)

          Country Alpha-2 code Alpha-3 code  Numeric
0     Afghanistan           AF          AFG        4
1   Åland Islands           AX          ALA      248
2         Albania           AL          ALB        8
3         Algeria           DZ          DZA       12
4  American Samoa           AS          ASM       16

In [ ]:
import pandas as pd

def q1_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean columns: strip, UPPER Alpha-2/Alpha-3, cast Numeric to int (nullable), drop invalids.
    """
    df_cleaned = df.copy()

    # Trim spaces from all string columns
    for col in df_cleaned.select_dtypes(include=['object']).columns:
        df_cleaned[col] = df_cleaned[col].astype(str).str.strip()

    # Convert Alpha-2 and Alpha-3 to UPPERCASE
    for col_name in ['Alpha-2 code', 'Alpha-3 code']:
        if col_name in df_cleaned.columns:
            df_cleaned[col_name] = df_cleaned[col_name].astype(str).str.upper()

    # Cast Numeric to nullable integer
    if 'Numeric' in df_cleaned.columns:
        df_cleaned['Numeric'] = pd.to_numeric(df_cleaned['Numeric'], errors='coerce').astype(pd.Int64Dtype())

    return df_cleaned

df_q1_cleaned = q1_clean(df_q1)
print("DataFrame cleaned.")
df_q1_cleaned.head()

DataFrame cleaned.

          Country Alpha-2 code Alpha-3 code  Numeric
0     Afghanistan           AF          AFG        4
1   Åland Islands           AX          ALA      248
2         Albania           AL          ALB        8
3         Algeria           DZ          DZA       12
4  American Samoa           AS          ASM       16

In [ ]:
def q1_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort descending by Numeric and return Top-N.
    """
    # Ensure 'Numeric' column exists and is sortable
    if 'Numeric' not in df.columns:
        raise ValueError("DataFrame must contain a 'Numeric' column.")

    # Sort by 'Numeric' descending, handling NaNs if any (they will go to the end)
    sorted_df = df.sort_values(by='Numeric', ascending=False, na_position='last')

    return sorted_df.head(top)


df_q1_top_15 = q1_sort_top(df_q1_cleaned)
print("Top 15 rows sorted by Numeric (descending):")
display(df_q1_top_15)

Top 15 rows sorted by Numeric (descending):

,Country,Alpha-2 code,Alpha-3 code,Numeric
247,Zambia,ZM,ZMB,894
246,Yemen,YE,YEM,887
192,Samoa,WS,WSM,882
244,Wallis and Futuna,WF,WLF,876
240,Venezuela (Bolivarian Republic of),VE,VEN,862
238,Uzbekistan,UZ,UZB,860
237,Uruguay,UY,URY,858
35,Burkina Faso,BF,BFA,854
243,Virgin Islands (U.S.),VI,VIR,850
236,United States of America (the),US,USA,840
219,"Tanzania, United Republic of",TZ,TZA,834
108,Isle of Man,IM,IMN,833
113,Jersey,JE,JEY,832
92,Guernsey,GG,GGY,831
234,United Kingdom of Great Britain and Northern I...,GB,GBR,826

In [ ]:
output_filename_q1 = 'data_q1.csv'
df_q1_cleaned.to_csv(output_filename_q1, index=False)
print(f"Cleaned data saved to {output_filename_q1}")

Cleaned data saved to data_q1.csv

## Question 2 — Hacker News (front page)
**URL:** https://news.ycombinator.com/  
**Extract at least:** `rank`, `title`, `link`, `points`, `comments` (user optional)  
**Clean:** cast `points`/`comments`/`rank` → **int** (non-digits → 0), fill missing text fields  
**Output:** write **`data_q2.csv`** and **print a Top-15** sorted by `points` (desc, no charts)  
**Tip:** Each story is a `.athing` row; details (points/comments/user) are in the next `<tr>` with `.subtext`.

In [ ]:
# --- Q2 Skeleton (fill the TODOs) ---
def q2_parse_items(html: str) -> pd.DataFrame:
    """Parse front page items into DataFrame columns:
       rank, title, link, points, comments, user (optional).
    TODO: implement with BeautifulSoup on '.athing' and its sibling '.subtext'.
    """
    raise NotImplementedError("TODO: implement q2_parse_items")

def q2_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean numeric fields and fill missing values.
    TODO: cast points/comments/rank to int (non-digits -> 0). Fill text fields.
    """
    raise NotImplementedError("TODO: implement q2_clean")

def q2_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort by points desc and return Top-N. TODO: implement."""
    raise NotImplementedError("TODO: implement q2_sort_top")

In [34]:
import pandas as pd
from bs4 import BeautifulSoup

# --- Q2 Skeleton (fill the TODOs) ---
def q2_parse_items(html: str) -> pd.DataFrame:
    """Parse front page items into DataFrame columns:
       rank, title, link, points, comments, user (optional).
    TODO: implement with BeautifulSoup on '.athing' and its sibling '.subtext'.
    """
    soup = BeautifulSoup(html, 'lxml')
    items_data = []

    stories = soup.find_all('tr', class_='athing')

    for story in stories:
        rank_tag = story.find('span', class_='rank')
        rank = rank_tag.text.replace('.', '') if rank_tag else None

        title_link_tag = story.find('span', class_='titleline')
        title = title_link_tag.find('a').text if title_link_tag and title_link_tag.find('a') else None
        link = title_link_tag.find('a')['href'] if title_link_tag and title_link_tag.find('a') else None

        # Details (points, comments, user) are in the next tr with .subtext
        subtext_row = story.find_next_sibling('tr')
        subtext_td = subtext_row.find('td', class_='subtext') if subtext_row else None

        points = None
        comments = None
        user = None

        if subtext_td:
            score_span = subtext_td.find('span', class_='score')
            if score_span:
                points_text = score_span.text.split(' ')[0]
                if points_text.isdigit():
                    points = int(points_text)

            comments_link = subtext_td.find('a', string=lambda text: text and 'comments' in text)
            if comments_link:
                # Extract numeric part from 'X comments' or 'discuss'
                comments_text = comments_link.text
                if 'comments' in comments_text:
                    try:
                        comments = int(comments_text.split(' ')[0])
                    except ValueError:
                        comments = 0 # Handle 'discuss' or other non-numeric cases
                elif 'discuss' in comments_text:
                    comments = 0 # No comments yet

            user_link = subtext_td.find('a', class_='hnuser')
            user = user_link.text if user_link else None

        items_data.append({
            'rank': rank,
            'title': title,
            'link': link,
            'points': points,
            'comments': comments,
            'user': user
        })

    # Filter out potential None rows if any parsing failed completely for a 'story' item
    items_data = [item for item in items_data if any(value is not None for value in item.values())]

    return pd.DataFrame(items_data)

def q2_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean numeric fields and fill missing values.
    TODO: cast points/comments/rank to int (non-digits -> 0). Fill text fields.
    """
    raise NotImplementedError("TODO: implement q2_clean")

def q2_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort by points desc and return Top-N. TODO: implement."""
    raise NotImplementedError("TODO: implement q2_sort_top")

In [35]:
URL_Q2 = "https://news.ycombinator.com/"
html_content_q2 = fetch_html(URL_Q2)
print("HTML content fetched for Question 2.")

HTML content fetched for Question 2.

In [27]:
import re, sys, pandas as pd, requests
from bs4 import BeautifulSoup
HEADERS = {"User-Agent": (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/122.0 Safari/537.36")}
def fetch_html(url: str, timeout: int = 20) -> str:
    r = requests.get(url, headers=HEADERS, timeout=timeout)
    r.raise_for_status()
    return r.text
def flatten_headers(df: pd.DataFrame) -> pd.DataFrame:
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [" ".join([str(x) for x in tup if str(x)!="nan"]).strip()
                      for tup in df.columns.values]
    else:
        df.columns = [str(c).strip() for c in df.columns]
    return df
print("Common helpers loaded.")

Common helpers loaded.

In [28]:
URL_Q2 = "https://news.ycombinator.com/"
html_content_q2 = fetch_html(URL_Q2)
print("HTML content fetched for Question 2.")

HTML content fetched for Question 2.

In [29]:
df_q2 = q2_parse_items(html_content_q2)
print("Hacker News items parsed into DataFrame.")
df_q2.head()

Hacker News items parsed into DataFrame.

,rank,title,link,points,comments,user
0,1,You should write an agent,https://fly.io/blog/everyone-write-an-agent/,338.0,0.0,tabletcorry
1,2,Scientists find ways to boost memory in aging ...,https://news.vt.edu/articles/2025/10/cals-jaro...,43.0,0.0,stevenjgarner
2,3,Two billion email addresses were exposed,https://www.troyhunt.com/2-billion-email-addre...,341.0,0.0,esnard
3,4,Game design is simple,https://www.raphkoster.com/2025/11/03/game-des...,114.0,0.0,vrnvu
4,5,"Kimi K2 Thinking, a SOTA open-source trillion-...",https://moonshotai.github.io/Kimi-K2/thinking....,591.0,0.0,nekofneko

In [30]:
import pandas as pd

def q2_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean numeric fields and fill missing values.
    Cast points/comments/rank to int (non-digits -> 0). Fill text fields.
    """
    df_cleaned = df.copy()

    # Cast numeric columns to int, coercing errors to 0
    for col in ['rank', 'points', 'comments']:
        if col in df_cleaned.columns:
            # Ensure 'rank' is treated as numeric before casting to int
            # For points/comments, we already tried to cast to int during parsing, but handle NaNs/None
            df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce').fillna(0).astype(int)

    # Fill missing text fields with an empty string or 'N/A'
    for col in ['title', 'link', 'user']:
        if col in df_cleaned.columns:
            df_cleaned[col] = df_cleaned[col].fillna('') # Or fill with 'N/A'

    return df_cleaned

df_q2_cleaned = q2_clean(df_q2)
print("Hacker News DataFrame cleaned.")
df_q2_cleaned.head()

Hacker News DataFrame cleaned.

,rank,title,link,points,comments,user
0,1,You should write an agent,https://fly.io/blog/everyone-write-an-agent/,338,0,tabletcorry
1,2,Scientists find ways to boost memory in aging ...,https://news.vt.edu/articles/2025/10/cals-jaro...,43,0,stevenjgarner
2,3,Two billion email addresses were exposed,https://www.troyhunt.com/2-billion-email-addre...,341,0,esnard
3,4,Game design is simple,https://www.raphkoster.com/2025/11/03/game-des...,114,0,vrnvu
4,5,"Kimi K2 Thinking, a SOTA open-source trillion-...",https://moonshotai.github.io/Kimi-K2/thinking....,591,0,nekofneko

In [31]:
import pandas as pd

def q2_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort by points desc and return Top-N."""
    if 'points' not in df.columns:
        raise ValueError("DataFrame must contain a 'points' column.")

    # Sort by 'points' descending. NaNs (if any, though cleaned to 0) would go to the end.
    sorted_df = df.sort_values(by='points', ascending=False)

    return sorted_df.head(top)

df_q2_top_15 = q2_sort_top(df_q2_cleaned)
print("Top 15 Hacker News stories sorted by points (descending):")
display(df_q2_top_15)

Top 15 Hacker News stories sorted by points (descending):

,rank,title,link,points,comments,user
15,16,FBI tries to unmask owner of archive.is,https://www.heise.de/en/news/Archive-today-FBI...,710,0,Projectiboga
4,5,"Kimi K2 Thinking, a SOTA open-source trillion-...",https://moonshotai.github.io/Kimi-K2/thinking....,591,0,nekofneko
20,21,ICC ditches Microsoft 365 for openDesk,https://www.binnenlandsbestuur.nl/digitaal/int...,531,0,vincvinc
9,10,Open Source Implementation of Apple's Private ...,https://github.com/openpcc/openpcc,358,0,adam_gyroscope
2,3,Two billion email addresses were exposed,https://www.troyhunt.com/2-billion-email-addre...,341,0,esnard
0,1,You should write an agent,https://fly.io/blog/everyone-write-an-agent/,338,0,tabletcorry
25,26,I may have found a way to spot U.S. at-sea str...,https://old.reddit.com/r/OSINT/comments/1opjjy...,306,0,hentrep
5,6,Show HN: I scraped 3B Goodreads reviews to tra...,https://book.sv,251,0,costco
19,20,Mathematical exploration and discovery at scale,https://terrytao.wordpress.com/2025/11/05/math...,227,0,nabla9
8,9,Swift on FreeBSD Preview,https://forums.swift.org/t/swift-on-freebsd-pr...,184,0,glhaynes
13,14,Eating stinging nettles,https://rachel.blog/2018/04/29/eating-stinging...,179,0,rzk
18,19,I analyzed the lineups at the most popular nig...,https://dev.karltryggvason.com/how-i-analyzed-...,140,0,kalli
29,30,"Show HN: qqqa – A fast, stateless LLM-powered ...",https://github.com/matisojka/qqqa,127,0,iagooar
3,4,Game design is simple,https://www.raphkoster.com/2025/11/03/game-des...,114,0,vrnvu
26,27,Show HN: See chords as flags – Visual harmony ...,https://rawl.rocks/,106,0,vitaly-pavlenko

In [32]:
output_filename_q2 = 'data_q2.csv'
df_q2_cleaned.to_csv(output_filename_q2, index=False)
print(f"Cleaned data for Q2 saved to {output_filename_q2}")

Cleaned data for Q2 saved to data_q2.csv