<a href="https://colab.research.google.com/github/KristinaA96/_DTSC3020_Fall2025/blob/main/Assignment_6_WebScraping_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 6 (4 points) — Web Scraping

In this assignment you will complete **two questions**. The **deadline is posted on Canvas**.

## Assignment Guide (Read Me First)

- This notebook provides an **Install Required Libraries** cell and a **Common Imports & Polite Headers** cell. Run them first.
- Each question includes a **skeleton**. The skeleton is **not** a solution; it is a lightweight scaffold you may reuse.
- Under each skeleton you will find a **“Write your answer here”** code cell. Implement your scraping, cleaning, and saving logic there.
- When your code is complete, run the **Runner** cell to print a Top‑15 preview and save the CSV.
- Expected outputs:
  - **Q1:** `data_q1.csv` + Top‑15 sorted by the specified numeric column.
  - **Q2:** `data_q2.csv` + Top‑15 sorted by `points`.

In [1]:
1) #Install Required Libraries
!pip -q install requests beautifulsoup4 lxml pandas
print("Dependencies installed.")

SyntaxError: unmatched ')' (ipython-input-565355372.py, line 1)

### 2) Common Imports & Polite Headers

In [ ]:
# Common Imports & Polite Headers
import re, sys, pandas as pd, requests
from bs4 import BeautifulSoup
HEADERS = {"User-Agent": (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/122.0 Safari/537.36")}
def fetch_html(url: str, timeout: int = 20) -> str:
    r = requests.get(url, headers=HEADERS, timeout=timeout)
    r.raise_for_status()
    return r.text
def flatten_headers(df: pd.DataFrame) -> pd.DataFrame:
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [" ".join([str(x) for x in tup if str(x)!="nan"]).strip()
                      for tup in df.columns.values]
    else:
        df.columns = [str(c).strip() for c in df.columns]
    return df
print("Common helpers loaded.")

## Question 1 — IBAN Country Codes (table)
**URL:** https://www.iban.com/country-codes  
**Extract at least:** `Country`, `Alpha-2`, `Alpha-3`, `Numeric` (≥4 cols; you may add more)  
**Clean:** trim spaces; `Alpha-2/Alpha-3` → **UPPERCASE**; `Numeric` → **int** (nullable OK)  
**Output:** write **`data_q1.csv`** and **print a Top-15** sorted by `Numeric` (desc, no charts)  
**Deliverables:** notebook + `data_q1.csv` + short `README.md` (URL, steps, 1 limitation)

**Tip:** You can use `pandas.read_html(html)` to read tables and then pick one with ≥3 columns.

In [ ]:
# --- Q1 Skeleton (fill the TODOs) ---
def q1_read_table(html: str) -> pd.DataFrame:
    """Return the first table with >= 3 columns from the HTML.
    TODO: implement with pd.read_html(html), pick a reasonable table, then flatten headers.
    """
    raise NotImplementedError("TODO: implement q1_read_table")

def q1_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean columns: strip, UPPER Alpha-2/Alpha-3, cast Numeric to int (nullable), drop invalids.
    TODO: implement cleaning steps.
    """
    raise NotImplementedError("TODO: implement q1_clean")

def q1_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort descending by Numeric and return Top-N.
    TODO: implement.
    """
    raise NotImplementedError("TODO: implement q1_sort_top")

In [17]:
URL_Q1 = "https://www.iban.com/country-codes"
html_content_q1 = fetch_html(URL_Q1)
print("HTML content fetched for Question 1.")

HTML content fetched for Question 1.

In [12]:
import requests

HEADERS = {"User-Agent": (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/122.0 Safari/537.36")}

def fetch_html(url: str, timeout: int = 20) -> str:
    r = requests.get(url, headers=HEADERS, timeout=timeout)
    r.raise_for_status()
    return r.text

URL_Q1 = "https://www.iban.com/country-codes"
html_content_q1 = fetch_html(URL_Q1)
print("HTML content fetched for Question 1.")

HTML content fetched for Question 1.

In [18]:
import pandas as pd

def flatten_headers(df: pd.DataFrame) -> pd.DataFrame:
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [" ".join([str(x) for x in tup if str(x)!="nan"]).strip()
                      for tup in df.columns.values]
    else:
        df.columns = [str(c).strip() for c in df.columns]
    return df

def q1_read_table(html: str) -> pd.DataFrame:
    dfs = pd.read_html(html)
    for df in dfs:
        if df.shape[1] >= 3:
            return flatten_headers(df)
    raise ValueError("No suitable table found with at least 3 columns.")

df_q1 = q1_read_table(html_content_q1)
print("Table extracted into DataFrame.")
df_q1.head()

Table extracted into DataFrame.

/tmp/ipython-input-1847083582.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(html)

          Country Alpha-2 code Alpha-3 code  Numeric
0     Afghanistan           AF          AFG        4
1   Åland Islands           AX          ALA      248
2         Albania           AL          ALB        8
3         Algeria           DZ          DZA       12
4  American Samoa           AS          ASM       16

In [19]:
import pandas as pd

def q1_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean columns: strip, UPPER Alpha-2/Alpha-3, cast Numeric to int (nullable), drop invalids.
    """
    df_cleaned = df.copy()

    # Trim spaces from all string columns
    for col in df_cleaned.select_dtypes(include=['object']).columns:
        df_cleaned[col] = df_cleaned[col].astype(str).str.strip()

    # Convert Alpha-2 and Alpha-3 to UPPERCASE
    for col_name in ['Alpha-2 code', 'Alpha-3 code']:
        if col_name in df_cleaned.columns:
            df_cleaned[col_name] = df_cleaned[col_name].astype(str).str.upper()

    # Cast Numeric to nullable integer
    if 'Numeric' in df_cleaned.columns:
        df_cleaned['Numeric'] = pd.to_numeric(df_cleaned['Numeric'], errors='coerce').astype(pd.Int64Dtype())

    return df_cleaned

df_q1_cleaned = q1_clean(df_q1)
print("DataFrame cleaned.")
df_q1_cleaned.head()

DataFrame cleaned.

          Country Alpha-2 code Alpha-3 code  Numeric
0     Afghanistan           AF          AFG        4
1   Åland Islands           AX          ALA      248
2         Albania           AL          ALB        8
3         Algeria           DZ          DZA       12
4  American Samoa           AS          ASM       16

In [15]:
def q1_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort descending by Numeric and return Top-N.
    """
    # Ensure 'Numeric' column exists and is sortable
    if 'Numeric' not in df.columns:
        raise ValueError("DataFrame must contain a 'Numeric' column.")

    # Sort by 'Numeric' descending, handling NaNs if any (they will go to the end)
    sorted_df = df.sort_values(by='Numeric', ascending=False, na_position='last')

    return sorted_df.head(top)


df_q1_top_15 = q1_sort_top(df_q1_cleaned)
print("Top 15 rows sorted by Numeric (descending):")
display(df_q1_top_15)

Top 15 rows sorted by Numeric (descending):

,Country,Alpha-2 code,Alpha-3 code,Numeric
247,Zambia,ZM,ZMB,894
246,Yemen,YE,YEM,887
192,Samoa,WS,WSM,882
244,Wallis and Futuna,WF,WLF,876
240,Venezuela (Bolivarian Republic of),VE,VEN,862
238,Uzbekistan,UZ,UZB,860
237,Uruguay,UY,URY,858
35,Burkina Faso,BF,BFA,854
243,Virgin Islands (U.S.),VI,VIR,850
236,United States of America (the),US,USA,840
219,"Tanzania, United Republic of",TZ,TZA,834
108,Isle of Man,IM,IMN,833
113,Jersey,JE,JEY,832
92,Guernsey,GG,GGY,831
234,United Kingdom of Great Britain and Northern I...,GB,GBR,826

In [16]:
output_filename_q1 = 'data_q1.csv'
df_q1_cleaned.to_csv(output_filename_q1, index=False)
print(f"Cleaned data saved to {output_filename_q1}")

Cleaned data saved to data_q1.csv

## Question 2 — Hacker News (front page)
**URL:** https://news.ycombinator.com/  
**Extract at least:** `rank`, `title`, `link`, `points`, `comments` (user optional)  
**Clean:** cast `points`/`comments`/`rank` → **int** (non-digits → 0), fill missing text fields  
**Output:** write **`data_q2.csv`** and **print a Top-15** sorted by `points` (desc, no charts)  
**Tip:** Each story is a `.athing` row; details (points/comments/user) are in the next `<tr>` with `.subtext`.

In [ ]:
# --- Q2 Skeleton (fill the TODOs) ---
def q2_parse_items(html: str) -> pd.DataFrame:
    """Parse front page items into DataFrame columns:
       rank, title, link, points, comments, user (optional).
    TODO: implement with BeautifulSoup on '.athing' and its sibling '.subtext'.
    """
    raise NotImplementedError("TODO: implement q2_parse_items")

def q2_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean numeric fields and fill missing values.
    TODO: cast points/comments/rank to int (non-digits -> 0). Fill text fields.
    """
    raise NotImplementedError("TODO: implement q2_clean")

def q2_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort by points desc and return Top-N. TODO: implement."""
    raise NotImplementedError("TODO: implement q2_sort_top")

In [20]:
URL_Q2 = "https://news.ycombinator.com/"
html_content_q2 = fetch_html(URL_Q2)
print("HTML content fetched for Question 2.")

HTML content fetched for Question 2.

In [21]:
from bs4 import BeautifulSoup

def q2_parse_items(html: str) -> pd.DataFrame:
    """Parse front page items into DataFrame columns:
       rank, title, link, points, comments, user (optional).
    """
    soup = BeautifulSoup(html, 'lxml')
    items = []

    # Each story is an '.athing' row
    for i, athing in enumerate(soup.find_all('tr', class_='athing')):
        story = {}
        # Rank
        rank_span = athing.find('span', class_='rank')
        story['rank'] = rank_span.get_text(strip=True).replace('.', '') if rank_span else ''

        # Title and Link
        title_link = athing.find('span', class_='titleline').find('a')
        story['title'] = title_link.get_text(strip=True) if title_link else ''
        story['link'] = title_link['href'] if title_link and 'href' in title_link.attrs else ''

        # Details (points, comments, user) are in the next '<tr>' with '.subtext'
        subtext_row = athing.next_sibling
        # Ensure subtext_row is a BeautifulSoup tag and has the 'subtext' class
        while subtext_row and (subtext_row.name != 'tr' or not subtext_row.find('td', class_='subtext')):
            subtext_row = subtext_row.next_sibling

        if subtext_row:
            subtext = subtext_row.find('td', class_='subtext')

            # Points
            score_span = subtext.find('span', class_='score')
            story['points'] = score_span.get_text(strip=True).replace(' points', '') if score_span else ''

            # User
            user_link = subtext.find('a', class_='hnuser')
            story['user'] = user_link.get_text(strip=True) if user_link else ''

            # Comments
            # Find the last 'a' tag in the subtext that typically contains comment count
            comments_link = None
            for a_tag in subtext.find_all('a'):
                if 'comment' in a_tag.get_text(): # Heuristic to find comments link
                    comments_link = a_tag

            if comments_link:
                comments_text = comments_link.get_text(strip=True)
                if 'discuss' in comments_text:
                    story['comments'] = '0' # No comments yet, just 'discuss'
                else:
                    story['comments'] = comments_text.replace('\xa0comments', '').replace(' comment', '')
            else:
                story['comments'] = ''
        else:
            story.update({'points': '', 'user': '', 'comments': ''})

        items.append(story)

    df_q2 = pd.DataFrame(items)
    return df_q2

df_q2 = q2_parse_items(html_content_q2)
print("HTML content parsed into DataFrame.")
df_q2.head()

HTML content parsed into DataFrame.

,rank,title,link,points,user,comments
0,1,You should write an agent,https://fly.io/blog/everyone-write-an-agent/,312,tabletcorry,153
1,2,Scientists find ways to boost memory in aging ...,https://news.vt.edu/articles/2025/10/cals-jaro...,32,stevenjgarner,3
2,3,"Kimi K2 Thinking, a SOTA open-source trillion-...",https://moonshotai.github.io/Kimi-K2/thinking....,583,nekofneko,233
3,4,Game design is simple,https://www.raphkoster.com/2025/11/03/game-des...,102,vrnvu,45
4,5,Two billion email addresses were exposed,https://www.troyhunt.com/2-billion-email-addre...,333,esnard,232

In [22]:
import pandas as pd

def q2_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Clean numeric fields and fill missing values.
    Cast points/comments/rank to int (non-digits -> 0). Fill text fields.
    """
    df_cleaned = df.copy()

    # Cast numeric fields to int, treating non-digits as 0
    numeric_cols = ['rank', 'points', 'comments']
    for col in numeric_cols:
        if col in df_cleaned.columns:
            # Use pd.to_numeric with errors='coerce' to turn non-numeric into NaN
            # then fill NaN with 0 and cast to Int64Dtype for nullable integers
            df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce').fillna(0).astype(pd.Int64Dtype())

    # Fill missing text fields with an empty string or 'N/A'
    # Assuming 'title', 'link', 'user' could be text fields
    text_cols = ['title', 'link', 'user']
    for col in text_cols:
        if col in df_cleaned.columns:
            df_cleaned[col] = df_cleaned[col].fillna('')
            # Ensure they are string type after filling (though fillna('') often maintains type)
            df_cleaned[col] = df_cleaned[col].astype(str)

    return df_cleaned

df_q2_cleaned = q2_clean(df_q2)
print("DataFrame cleaned.")
df_q2_cleaned.head()

DataFrame cleaned.

,rank,title,link,points,user,comments
0,1,You should write an agent,https://fly.io/blog/everyone-write-an-agent/,312,tabletcorry,153
1,2,Scientists find ways to boost memory in aging ...,https://news.vt.edu/articles/2025/10/cals-jaro...,32,stevenjgarner,3
2,3,"Kimi K2 Thinking, a SOTA open-source trillion-...",https://moonshotai.github.io/Kimi-K2/thinking....,583,nekofneko,233
3,4,Game design is simple,https://www.raphkoster.com/2025/11/03/game-des...,102,vrnvu,45
4,5,Two billion email addresses were exposed,https://www.troyhunt.com/2-billion-email-addre...,333,esnard,232

In [23]:
def q2_sort_top(df: pd.DataFrame, top: int = 15) -> pd.DataFrame:
    """Sort by points desc and return Top-N."""
    # Ensure 'points' column exists and is sortable
    if 'points' not in df.columns:
        raise ValueError("DataFrame must contain a 'points' column.")

    # Sort by 'points' descending
    sorted_df = df.sort_values(by='points', ascending=False)

    return sorted_df.head(top)

df_q2_top_15 = q2_sort_top(df_q2_cleaned)
print("Top 15 rows sorted by points (descending):")
display(df_q2_top_15)

Top 15 rows sorted by points (descending):

,rank,title,link,points,user,comments
12,13,FBI tries to unmask owner of archive.is,https://www.heise.de/en/news/Archive-today-FBI...,705,Projectiboga,371
2,3,"Kimi K2 Thinking, a SOTA open-source trillion-...",https://moonshotai.github.io/Kimi-K2/thinking....,583,nekofneko,233
18,19,ICC ditches Microsoft 365 for openDesk,https://www.binnenlandsbestuur.nl/digitaal/int...,530,vincvinc,164
8,9,Open Source Implementation of Apple's Private ...,https://github.com/openpcc/openpcc,358,adam_gyroscope,71
4,5,Two billion email addresses were exposed,https://www.troyhunt.com/2-billion-email-addre...,333,esnard,232
0,1,You should write an agent,https://fly.io/blog/everyone-write-an-agent/,312,tabletcorry,153
23,24,I may have found a way to spot U.S. at-sea str...,https://old.reddit.com/r/OSINT/comments/1opjjy...,304,hentrep,427
5,6,Show HN: I scraped 3B Goodreads reviews to tra...,https://book.sv,243,costco,92
19,20,Mathematical exploration and discovery at scale,https://terrytao.wordpress.com/2025/11/05/math...,225,nabla9,111
7,8,Swift on FreeBSD Preview,https://forums.swift.org/t/swift-on-freebsd-pr...,184,glhaynes,103
14,15,Eating stinging nettles,https://rachel.blog/2018/04/29/eating-stinging...,172,rzk,166
16,17,I analyzed the lineups at the most popular nig...,https://dev.karltryggvason.com/how-i-analyzed-...,140,kalli,69
28,29,"Show HN: qqqa – A fast, stateless LLM-powered ...",https://github.com/matisojka/qqqa,127,iagooar,79
24,25,Show HN: See chords as flags – Visual harmony ...,https://rawl.rocks/,106,vitaly-pavlenko,27
3,4,Game design is simple,https://www.raphkoster.com/2025/11/03/game-des...,102,vrnvu,45

In [24]:
output_filename_q2 = 'data_q2.csv'
df_q2_cleaned.to_csv(output_filename_q2, index=False)
print(f"Cleaned data saved to {output_filename_q2}")

Cleaned data saved to data_q2.csv